version: '3.1'



networks:
  net1:

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19021980Kv
      POSTGRES_DB: aiohttp
    ports:
      - 5431:5433
    networks:
      net1:
        aliases:
          - database

  app:
    build:
      context: .
      args:
        DB: 'postgres://postgres:19021980Kv@database/aiohttp'
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    container_name: app

    depends_on:
      - db
    networks:
      net1:
        aliases:
          - app
    volumes:
      - ./:/code

